// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'third_party/ark_wallet/ark/balance.dart';
import 'third_party/ark_wallet/ark/client.dart';
import 'third_party/ark_wallet/ark/esplora.dart';
import 'third_party/ark_wallet/ark/server_info.dart';
import 'third_party/ark_wallet/ark/settle.dart';
import 'third_party/ark_wallet/ark/storage.dart';
import 'third_party/ark_wallet/ark/utils.dart';
import 'third_party/bbqr/continuous_join.dart';
import 'third_party/bbqr/encode.dart';
import 'third_party/bbqr/file_type.dart';
import 'third_party/bbqr/join.dart';
import 'third_party/bbqr/qr.dart';
import 'third_party/bbqr/split.dart';
import 'third_party/bitbox/api.dart';
import 'third_party/dart_bbqr/api.dart';

abstract class BullSdkApiImplPlatform extends BaseApiImpl<BullSdkWire> {
  BullSdkApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArkWalletPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWalletPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ContinuousJoinResultPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResultPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ContinuousJoinerPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinerPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_EsploraClientPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClientPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_InMemoryDbPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDbPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ArkWallet
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    dynamic raw,
  );

  @protected
  ContinuousJoinResult
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
    dynamic raw,
  );

  @protected
  ContinuousJoiner
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    dynamic raw,
  );

  @protected
  EsploraClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    dynamic raw,
  );

  @protected
  InMemoryDb
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb(
    dynamic raw,
  );

  @protected
  ContinuousJoiner
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    dynamic raw,
  );

  @protected
  ArkWallet
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    dynamic raw,
  );

  @protected
  EsploraClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    dynamic raw,
  );

  @protected
  ArkWallet
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    dynamic raw,
  );

  @protected
  ContinuousJoinResult
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
    dynamic raw,
  );

  @protected
  ContinuousJoiner
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    dynamic raw,
  );

  @protected
  EsploraClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    dynamic raw,
  );

  @protected
  InMemoryDb
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ContinuousJoinerExt dco_decode_TraitDef_ContinuousJoinerExt(dynamic raw);

  @protected
  JoinedExt dco_decode_TraitDef_JoinedExt(dynamic raw);

  @protected
  SplitExt dco_decode_TraitDef_SplitExt(dynamic raw);

  @protected
  ArkBalance dco_decode_ark_balance(dynamic raw);

  @protected
  ArkBoarding dco_decode_ark_boarding(dynamic raw);

  @protected
  ArkTransaction dco_decode_ark_transaction(dynamic raw);

  @protected
  BoardingSettlement dco_decode_boarding_settlement(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Encoding dco_decode_box_autoadd_encoding(dynamic raw);

  @protected
  FileType dco_decode_box_autoadd_file_type(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  SplitOptions dco_decode_box_autoadd_split_options(dynamic raw);

  @protected
  DeviceInfo dco_decode_device_info(dynamic raw);

  @protected
  Encoding dco_decode_encoding(dynamic raw);

  @protected
  FileType dco_decode_file_type(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Joined dco_decode_joined(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ArkTransaction> dco_decode_list_ark_transaction(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Encoding? dco_decode_opt_box_autoadd_encoding(dynamic raw);

  @protected
  FileType? dco_decode_opt_box_autoadd_file_type(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  ServerInfo dco_decode_server_info(dynamic raw);

  @protected
  Split dco_decode_split(dynamic raw);

  @protected
  SplitOptions dco_decode_split_options(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Utils dco_decode_utils(dynamic raw);

  @protected
  Version dco_decode_version(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ArkWallet
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    SseDeserializer deserializer,
  );

  @protected
  ContinuousJoinResult
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
    SseDeserializer deserializer,
  );

  @protected
  ContinuousJoiner
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    SseDeserializer deserializer,
  );

  @protected
  EsploraClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    SseDeserializer deserializer,
  );

  @protected
  InMemoryDb
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb(
    SseDeserializer deserializer,
  );

  @protected
  ContinuousJoiner
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    SseDeserializer deserializer,
  );

  @protected
  ArkWallet
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    SseDeserializer deserializer,
  );

  @protected
  EsploraClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    SseDeserializer deserializer,
  );

  @protected
  ArkWallet
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    SseDeserializer deserializer,
  );

  @protected
  ContinuousJoinResult
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
    SseDeserializer deserializer,
  );

  @protected
  ContinuousJoiner
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    SseDeserializer deserializer,
  );

  @protected
  EsploraClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    SseDeserializer deserializer,
  );

  @protected
  InMemoryDb
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ArkBalance sse_decode_ark_balance(SseDeserializer deserializer);

  @protected
  ArkBoarding sse_decode_ark_boarding(SseDeserializer deserializer);

  @protected
  ArkTransaction sse_decode_ark_transaction(SseDeserializer deserializer);

  @protected
  BoardingSettlement sse_decode_boarding_settlement(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Encoding sse_decode_box_autoadd_encoding(SseDeserializer deserializer);

  @protected
  FileType sse_decode_box_autoadd_file_type(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SplitOptions sse_decode_box_autoadd_split_options(
    SseDeserializer deserializer,
  );

  @protected
  DeviceInfo sse_decode_device_info(SseDeserializer deserializer);

  @protected
  Encoding sse_decode_encoding(SseDeserializer deserializer);

  @protected
  FileType sse_decode_file_type(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Joined sse_decode_joined(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ArkTransaction> sse_decode_list_ark_transaction(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Encoding? sse_decode_opt_box_autoadd_encoding(SseDeserializer deserializer);

  @protected
  FileType? sse_decode_opt_box_autoadd_file_type(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ServerInfo sse_decode_server_info(SseDeserializer deserializer);

  @protected
  Split sse_decode_split(SseDeserializer deserializer);

  @protected
  SplitOptions sse_decode_split_options(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Utils sse_decode_utils(SseDeserializer deserializer);

  @protected
  Version sse_decode_version(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
    AnyhowException raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_box_autoadd_encoding(Encoding raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_encoding(cst_encode_encoding(raw));
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_box_autoadd_file_type(FileType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_file_type(cst_encode_file_type(raw));
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_64(cst_encode_i_64(raw));
  }

  @protected
  ffi.Pointer<wire_cst_split_options> cst_encode_box_autoadd_split_options(
    SplitOptions raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_split_options();
    cst_api_fill_to_wire_split_options(raw, ptr.ref);
    return ptr;
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_ark_transaction> cst_encode_list_ark_transaction(
    List<ArkTransaction> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_ark_transaction(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_ark_transaction(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
    List<int> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_opt_box_autoadd_encoding(Encoding? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_encoding(raw);
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_opt_box_autoadd_file_type(FileType? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_file_type(raw);
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
  cst_encode_opt_list_prim_u_8_strict(Uint8List? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_list_prim_u_8_strict(raw);
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_ark_balance(
    ArkBalance apiObj,
    wire_cst_ark_balance wireObj,
  ) {
    wireObj.preconfirmed = cst_encode_i_64(apiObj.preconfirmed);
    wireObj.settled = cst_encode_i_64(apiObj.settled);
    wireObj.available = cst_encode_i_64(apiObj.available);
    wireObj.recoverable = cst_encode_i_64(apiObj.recoverable);
    wireObj.total = cst_encode_i_64(apiObj.total);
    cst_api_fill_to_wire_ark_boarding(apiObj.boarding, wireObj.boarding);
  }

  @protected
  void cst_api_fill_to_wire_ark_boarding(
    ArkBoarding apiObj,
    wire_cst_ark_boarding wireObj,
  ) {
    wireObj.unconfirmed = cst_encode_i_64(apiObj.unconfirmed);
    wireObj.confirmed = cst_encode_i_64(apiObj.confirmed);
    wireObj.total = cst_encode_i_64(apiObj.total);
  }

  @protected
  void cst_api_fill_to_wire_ark_transaction(
    ArkTransaction apiObj,
    wire_cst_ark_transaction wireObj,
  ) {
    if (apiObj is ArkTransaction_Boarding) {
      var pre_txid = cst_encode_String(apiObj.txid);
      var pre_sats = cst_encode_i_64(apiObj.sats);
      var pre_confirmed_at = cst_encode_opt_box_autoadd_i_64(
        apiObj.confirmedAt,
      );
      wireObj.tag = 0;
      wireObj.kind.Boarding.txid = pre_txid;
      wireObj.kind.Boarding.sats = pre_sats;
      wireObj.kind.Boarding.confirmed_at = pre_confirmed_at;
      return;
    }
    if (apiObj is ArkTransaction_Commitment) {
      var pre_txid = cst_encode_String(apiObj.txid);
      var pre_sats = cst_encode_i_64(apiObj.sats);
      var pre_created_at = cst_encode_i_64(apiObj.createdAt);
      wireObj.tag = 1;
      wireObj.kind.Commitment.txid = pre_txid;
      wireObj.kind.Commitment.sats = pre_sats;
      wireObj.kind.Commitment.created_at = pre_created_at;
      return;
    }
    if (apiObj is ArkTransaction_Redeem) {
      var pre_txid = cst_encode_String(apiObj.txid);
      var pre_sats = cst_encode_i_64(apiObj.sats);
      var pre_is_settled = cst_encode_bool(apiObj.isSettled);
      var pre_created_at = cst_encode_i_64(apiObj.createdAt);
      wireObj.tag = 2;
      wireObj.kind.Redeem.txid = pre_txid;
      wireObj.kind.Redeem.sats = pre_sats;
      wireObj.kind.Redeem.is_settled = pre_is_settled;
      wireObj.kind.Redeem.created_at = pre_created_at;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_boarding_settlement(
    BoardingSettlement apiObj,
    wire_cst_boarding_settlement wireObj,
  ) {
    wireObj.pending_count = cst_encode_i_32(apiObj.pendingCount);
    wireObj.confirmed_count = cst_encode_i_32(apiObj.confirmedCount);
    wireObj.total_pending_sats = cst_encode_i_64(apiObj.totalPendingSats);
    wireObj.total_confirmed_sats = cst_encode_i_64(apiObj.totalConfirmedSats);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_split_options(
    SplitOptions apiObj,
    ffi.Pointer<wire_cst_split_options> wireObj,
  ) {
    cst_api_fill_to_wire_split_options(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_device_info(
    DeviceInfo apiObj,
    wire_cst_device_info wireObj,
  ) {
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.version = cst_encode_String(apiObj.version);
    wireObj.initialized = cst_encode_bool(apiObj.initialized);
  }

  @protected
  void cst_api_fill_to_wire_joined(Joined apiObj, wire_cst_joined wireObj) {
    wireObj.encoding = cst_encode_encoding(apiObj.encoding);
    wireObj.file_type = cst_encode_file_type(apiObj.fileType);
    wireObj.data = cst_encode_list_prim_u_8_strict(apiObj.data);
  }

  @protected
  void cst_api_fill_to_wire_server_info(
    ServerInfo apiObj,
    wire_cst_server_info wireObj,
  ) {
    wireObj.version = cst_encode_String(apiObj.version);
    wireObj.signer_pubkey = cst_encode_String(apiObj.signerPubkey);
    wireObj.forfeit_pubkey = cst_encode_String(apiObj.forfeitPubkey);
    wireObj.forfeit_address = cst_encode_String(apiObj.forfeitAddress);
    wireObj.checkpoint_tapscript = cst_encode_String(
      apiObj.checkpointTapscript,
    );
    wireObj.network = cst_encode_String(apiObj.network);
    wireObj.session_duration = cst_encode_i_64(apiObj.sessionDuration);
    wireObj.unilateral_exit_delay = cst_encode_u_32(apiObj.unilateralExitDelay);
    wireObj.boarding_exit_delay = cst_encode_u_32(apiObj.boardingExitDelay);
    wireObj.utxo_min_amount = cst_encode_opt_box_autoadd_i_64(
      apiObj.utxoMinAmount,
    );
    wireObj.utxo_max_amount = cst_encode_opt_box_autoadd_i_64(
      apiObj.utxoMaxAmount,
    );
    wireObj.vtxo_min_amount = cst_encode_opt_box_autoadd_i_64(
      apiObj.vtxoMinAmount,
    );
    wireObj.vtxo_max_amount = cst_encode_opt_box_autoadd_i_64(
      apiObj.vtxoMaxAmount,
    );
    wireObj.dust = cst_encode_i_64(apiObj.dust);
    wireObj.digest = cst_encode_String(apiObj.digest);
  }

  @protected
  void cst_api_fill_to_wire_split(Split apiObj, wire_cst_split wireObj) {
    wireObj.version = cst_encode_version(apiObj.version);
    wireObj.parts = cst_encode_list_String(apiObj.parts);
    wireObj.encoding = cst_encode_encoding(apiObj.encoding);
  }

  @protected
  void cst_api_fill_to_wire_split_options(
    SplitOptions apiObj,
    wire_cst_split_options wireObj,
  ) {
    wireObj.encoding = cst_encode_encoding(apiObj.encoding);
    wireObj.min_split_number = cst_encode_usize(apiObj.minSplitNumber);
    wireObj.max_split_number = cst_encode_usize(apiObj.maxSplitNumber);
    wireObj.min_version = cst_encode_version(apiObj.minVersion);
    wireObj.max_version = cst_encode_version(apiObj.maxVersion);
  }

  @protected
  void cst_api_fill_to_wire_utils(Utils apiObj, wire_cst_utils wireObj) {}

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    ArkWallet raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
    ContinuousJoinResult raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    ContinuousJoiner raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    EsploraClient raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb(
    InMemoryDb raw,
  );

  @protected
  int
  cst_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    ContinuousJoiner raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    ArkWallet raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    EsploraClient raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    ArkWallet raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
    ContinuousJoinResult raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    ContinuousJoiner raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    EsploraClient raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb(
    InMemoryDb raw,
  );

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_encoding(Encoding raw);

  @protected
  int cst_encode_file_type(FileType raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  int cst_encode_version(Version raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    ArkWallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
    ContinuousJoinResult self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    ContinuousJoiner self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    EsploraClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb(
    InMemoryDb self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    ContinuousJoiner self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    ArkWallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    EsploraClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    ArkWallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
    ContinuousJoinResult self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    ContinuousJoiner self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    EsploraClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb(
    InMemoryDb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ark_balance(ArkBalance self, SseSerializer serializer);

  @protected
  void sse_encode_ark_boarding(ArkBoarding self, SseSerializer serializer);

  @protected
  void sse_encode_ark_transaction(
    ArkTransaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_boarding_settlement(
    BoardingSettlement self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_encoding(Encoding self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_file_type(
    FileType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_split_options(
    SplitOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_info(DeviceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_encoding(Encoding self, SseSerializer serializer);

  @protected
  void sse_encode_file_type(FileType self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_joined(Joined self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ark_transaction(
    List<ArkTransaction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_encoding(
    Encoding? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_file_type(
    FileType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_server_info(ServerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_split(Split self, SseSerializer serializer);

  @protected
  void sse_encode_split_options(SplitOptions self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_utils(Utils self, SseSerializer serializer);

  @protected
  void sse_encode_version(Version self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class BullSdkWire implements BaseWire {
  factory BullSdkWire.fromExternalLibrary(ExternalLibrary lib) =>
      BullSdkWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BullSdkWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  BullSdkWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__ark_wallet__ark__client__ArkWallet_balance(int port_, int that) {
    return _wire__ark_wallet__ark__client__ArkWallet_balance(port_, that);
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_balancePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_balance',
      );
  late final _wire__ark_wallet__ark__client__ArkWallet_balance =
      _wire__ark_wallet__ark__client__ArkWallet_balancePtr
          .asFunction<void Function(int, int)>();

  WireSyncRust2DartDco
  wire__ark_wallet__ark__client__ArkWallet_boarding_address(int that) {
    return _wire__ark_wallet__ark__client__ArkWallet_boarding_address(that);
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_boarding_addressPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_boarding_address',
      );
  late final _wire__ark_wallet__ark__client__ArkWallet_boarding_address =
      _wire__ark_wallet__ark__client__ArkWallet_boarding_addressPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  void wire__ark_wallet__ark__client__ArkWallet_can_settle_boarding(
    int port_,
    int that,
  ) {
    return _wire__ark_wallet__ark__client__ArkWallet_can_settle_boarding(
      port_,
      that,
    );
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_can_settle_boardingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_can_settle_boarding',
      );
  late final _wire__ark_wallet__ark__client__ArkWallet_can_settle_boarding =
      _wire__ark_wallet__ark__client__ArkWallet_can_settle_boardingPtr
          .asFunction<void Function(int, int)>();

  void wire__ark_wallet__ark__client__ArkWallet_collaborative_redeem(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> address,
    int sats,
    bool select_recoverable_vtxos,
  ) {
    return _wire__ark_wallet__ark__client__ArkWallet_collaborative_redeem(
      port_,
      that,
      address,
      sats,
      select_recoverable_vtxos,
    );
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_collaborative_redeemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Int64,
            ffi.Bool,
          )
        >
      >(
        'frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_collaborative_redeem',
      );
  late final _wire__ark_wallet__ark__client__ArkWallet_collaborative_redeem =
      _wire__ark_wallet__ark__client__ArkWallet_collaborative_redeemPtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              bool,
            )
          >();

  void wire__ark_wallet__ark__client__ArkWallet_get_boarding_status(
    int port_,
    int that,
  ) {
    return _wire__ark_wallet__ark__client__ArkWallet_get_boarding_status(
      port_,
      that,
    );
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_get_boarding_statusPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_get_boarding_status',
      );
  late final _wire__ark_wallet__ark__client__ArkWallet_get_boarding_status =
      _wire__ark_wallet__ark__client__ArkWallet_get_boarding_statusPtr
          .asFunction<void Function(int, int)>();

  void wire__ark_wallet__ark__client__ArkWallet_init(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> secret_key,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> network,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> esplora,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> server,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> boltz,
  ) {
    return _wire__ark_wallet__ark__client__ArkWallet_init(
      port_,
      secret_key,
      network,
      esplora,
      server,
      boltz,
    );
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_init');
  late final _wire__ark_wallet__ark__client__ArkWallet_init =
      _wire__ark_wallet__ark__client__ArkWallet_initPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco
  wire__ark_wallet__ark__client__ArkWallet_offchain_address(int that) {
    return _wire__ark_wallet__ark__client__ArkWallet_offchain_address(that);
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_offchain_addressPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_offchain_address',
      );
  late final _wire__ark_wallet__ark__client__ArkWallet_offchain_address =
      _wire__ark_wallet__ark__client__ArkWallet_offchain_addressPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__ark_wallet__ark__client__ArkWallet_onchain_address(
    int that,
  ) {
    return _wire__ark_wallet__ark__client__ArkWallet_onchain_address(that);
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_onchain_addressPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_onchain_address',
      );
  late final _wire__ark_wallet__ark__client__ArkWallet_onchain_address =
      _wire__ark_wallet__ark__client__ArkWallet_onchain_addressPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  void wire__ark_wallet__ark__client__ArkWallet_send_off_chain(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> address,
    int sats,
  ) {
    return _wire__ark_wallet__ark__client__ArkWallet_send_off_chain(
      port_,
      that,
      address,
      sats,
    );
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_send_off_chainPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Int64,
          )
        >
      >(
        'frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_send_off_chain',
      );
  late final _wire__ark_wallet__ark__client__ArkWallet_send_off_chain =
      _wire__ark_wallet__ark__client__ArkWallet_send_off_chainPtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
            )
          >();

  void wire__ark_wallet__ark__client__ArkWallet_send_on_chain(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> address,
    int sats,
  ) {
    return _wire__ark_wallet__ark__client__ArkWallet_send_on_chain(
      port_,
      that,
      address,
      sats,
    );
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_send_on_chainPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Int64,
          )
        >
      >(
        'frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_send_on_chain',
      );
  late final _wire__ark_wallet__ark__client__ArkWallet_send_on_chain =
      _wire__ark_wallet__ark__client__ArkWallet_send_on_chainPtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
            )
          >();

  WireSyncRust2DartDco wire__ark_wallet__ark__client__ArkWallet_server_info(
    int that,
  ) {
    return _wire__ark_wallet__ark__client__ArkWallet_server_info(that);
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_server_infoPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_server_info',
      );
  late final _wire__ark_wallet__ark__client__ArkWallet_server_info =
      _wire__ark_wallet__ark__client__ArkWallet_server_infoPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  void wire__ark_wallet__ark__client__ArkWallet_settle(
    int port_,
    int that,
    bool select_recoverable_vtxos,
  ) {
    return _wire__ark_wallet__ark__client__ArkWallet_settle(
      port_,
      that,
      select_recoverable_vtxos,
    );
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_settlePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Bool)>
      >('frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_settle');
  late final _wire__ark_wallet__ark__client__ArkWallet_settle =
      _wire__ark_wallet__ark__client__ArkWallet_settlePtr
          .asFunction<void Function(int, int, bool)>();

  void wire__ark_wallet__ark__client__ArkWallet_settle_boarding_transactions(
    int port_,
    int that,
    bool select_recoverable_vtxos,
  ) {
    return _wire__ark_wallet__ark__client__ArkWallet_settle_boarding_transactions(
      port_,
      that,
      select_recoverable_vtxos,
    );
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_settle_boarding_transactionsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Bool)>
      >(
        'frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_settle_boarding_transactions',
      );
  late final _wire__ark_wallet__ark__client__ArkWallet_settle_boarding_transactions =
      _wire__ark_wallet__ark__client__ArkWallet_settle_boarding_transactionsPtr
          .asFunction<void Function(int, int, bool)>();

  void wire__ark_wallet__ark__client__ArkWallet_transaction_history(
    int port_,
    int that,
  ) {
    return _wire__ark_wallet__ark__client__ArkWallet_transaction_history(
      port_,
      that,
    );
  }

  late final _wire__ark_wallet__ark__client__ArkWallet_transaction_historyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_bull_sdk_wire__ark_wallet__ark__client__ArkWallet_transaction_history',
      );
  late final _wire__ark_wallet__ark__client__ArkWallet_transaction_history =
      _wire__ark_wallet__ark__client__ArkWallet_transaction_historyPtr
          .asFunction<void Function(int, int)>();

  void wire__bbqr__continuous_join__ContinuousJoiner_default(int port_) {
    return _wire__bbqr__continuous_join__ContinuousJoiner_default(port_);
  }

  late final _wire__bbqr__continuous_join__ContinuousJoiner_defaultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_bull_sdk_wire__bbqr__continuous_join__ContinuousJoiner_default',
      );
  late final _wire__bbqr__continuous_join__ContinuousJoiner_default =
      _wire__bbqr__continuous_join__ContinuousJoiner_defaultPtr
          .asFunction<void Function(int)>();

  void wire__bbqr__continuous_join__ContinuousJoiner_frb_override_add_part(
    int port_,
    int that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> part,
  ) {
    return _wire__bbqr__continuous_join__ContinuousJoiner_frb_override_add_part(
      port_,
      that,
      part,
    );
  }

  late final _wire__bbqr__continuous_join__ContinuousJoiner_frb_override_add_partPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_bull_sdk_wire__bbqr__continuous_join__ContinuousJoiner_frb_override_add_part',
      );
  late final _wire__bbqr__continuous_join__ContinuousJoiner_frb_override_add_part =
      _wire__bbqr__continuous_join__ContinuousJoiner_frb_override_add_partPtr
          .asFunction<
            void Function(int, int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__bbqr__continuous_join__ContinuousJoiner_new(int port_) {
    return _wire__bbqr__continuous_join__ContinuousJoiner_new(port_);
  }

  late final _wire__bbqr__continuous_join__ContinuousJoiner_newPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_bull_sdk_wire__bbqr__continuous_join__ContinuousJoiner_new',
      );
  late final _wire__bbqr__continuous_join__ContinuousJoiner_new =
      _wire__bbqr__continuous_join__ContinuousJoiner_newPtr
          .asFunction<void Function(int)>();

  void wire__ark_wallet__ark__esplora__EsploraClient_check_connection(
    int port_,
    int that,
  ) {
    return _wire__ark_wallet__ark__esplora__EsploraClient_check_connection(
      port_,
      that,
    );
  }

  late final _wire__ark_wallet__ark__esplora__EsploraClient_check_connectionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_bull_sdk_wire__ark_wallet__ark__esplora__EsploraClient_check_connection',
      );
  late final _wire__ark_wallet__ark__esplora__EsploraClient_check_connection =
      _wire__ark_wallet__ark__esplora__EsploraClient_check_connectionPtr
          .asFunction<void Function(int, int)>();

  void wire__ark_wallet__ark__esplora__EsploraClient_new(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> url,
  ) {
    return _wire__ark_wallet__ark__esplora__EsploraClient_new(port_, url);
  }

  late final _wire__ark_wallet__ark__esplora__EsploraClient_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__ark_wallet__ark__esplora__EsploraClient_new');
  late final _wire__ark_wallet__ark__esplora__EsploraClient_new =
      _wire__ark_wallet__ark__esplora__EsploraClient_newPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__ark_wallet__ark__storage__InMemoryDb_default(int port_) {
    return _wire__ark_wallet__ark__storage__InMemoryDb_default(port_);
  }

  late final _wire__ark_wallet__ark__storage__InMemoryDb_defaultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_bull_sdk_wire__ark_wallet__ark__storage__InMemoryDb_default',
      );
  late final _wire__ark_wallet__ark__storage__InMemoryDb_default =
      _wire__ark_wallet__ark__storage__InMemoryDb_defaultPtr
          .asFunction<void Function(int)>();

  void wire__bitbox__api__close_device(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> serial_number,
  ) {
    return _wire__bitbox__api__close_device(port_, serial_number);
  }

  late final _wire__bitbox__api__close_devicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__bitbox__api__close_device');
  late final _wire__bitbox__api__close_device =
      _wire__bitbox__api__close_devicePtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__bitbox__api__close_usb_channel(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> serial_number,
  ) {
    return _wire__bitbox__api__close_usb_channel(port_, serial_number);
  }

  late final _wire__bitbox__api__close_usb_channelPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__bitbox__api__close_usb_channel');
  late final _wire__bitbox__api__close_usb_channel =
      _wire__bitbox__api__close_usb_channelPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__bitbox__api__confirm_pairing(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> serial_number,
  ) {
    return _wire__bitbox__api__confirm_pairing(port_, serial_number);
  }

  late final _wire__bitbox__api__confirm_pairingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__bitbox__api__confirm_pairing');
  late final _wire__bitbox__api__confirm_pairing =
      _wire__bitbox__api__confirm_pairingPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__bbqr__encode__encoding_as_byte(int port_, int that) {
    return _wire__bbqr__encode__encoding_as_byte(port_, that);
  }

  late final _wire__bbqr__encode__encoding_as_bytePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
        'frbgen_bull_sdk_wire__bbqr__encode__encoding_as_byte',
      );
  late final _wire__bbqr__encode__encoding_as_byte =
      _wire__bbqr__encode__encoding_as_bytePtr
          .asFunction<void Function(int, int)>();

  void wire__bbqr__encode__encoding_from_byte(int port_, int byte) {
    return _wire__bbqr__encode__encoding_from_byte(port_, byte);
  }

  late final _wire__bbqr__encode__encoding_from_bytePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Uint8)>>(
        'frbgen_bull_sdk_wire__bbqr__encode__encoding_from_byte',
      );
  late final _wire__bbqr__encode__encoding_from_byte =
      _wire__bbqr__encode__encoding_from_bytePtr
          .asFunction<void Function(int, int)>();

  void wire__bbqr__encode__encoding_is_known_encoding(int port_, int byte) {
    return _wire__bbqr__encode__encoding_is_known_encoding(port_, byte);
  }

  late final _wire__bbqr__encode__encoding_is_known_encodingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Uint8)>>(
        'frbgen_bull_sdk_wire__bbqr__encode__encoding_is_known_encoding',
      );
  late final _wire__bbqr__encode__encoding_is_known_encoding =
      _wire__bbqr__encode__encoding_is_known_encodingPtr
          .asFunction<void Function(int, int)>();

  void wire__bbqr__encode__encoding_split_mod(int port_, int that) {
    return _wire__bbqr__encode__encoding_split_mod(port_, that);
  }

  late final _wire__bbqr__encode__encoding_split_modPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
        'frbgen_bull_sdk_wire__bbqr__encode__encoding_split_mod',
      );
  late final _wire__bbqr__encode__encoding_split_mod =
      _wire__bbqr__encode__encoding_split_modPtr
          .asFunction<void Function(int, int)>();

  void wire__bbqr__file_type__file_type_as_byte(int port_, int that) {
    return _wire__bbqr__file_type__file_type_as_byte(port_, that);
  }

  late final _wire__bbqr__file_type__file_type_as_bytePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
        'frbgen_bull_sdk_wire__bbqr__file_type__file_type_as_byte',
      );
  late final _wire__bbqr__file_type__file_type_as_byte =
      _wire__bbqr__file_type__file_type_as_bytePtr
          .asFunction<void Function(int, int)>();

  void wire__bbqr__file_type__file_type_from_byte(int port_, int byte) {
    return _wire__bbqr__file_type__file_type_from_byte(port_, byte);
  }

  late final _wire__bbqr__file_type__file_type_from_bytePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Uint8)>>(
        'frbgen_bull_sdk_wire__bbqr__file_type__file_type_from_byte',
      );
  late final _wire__bbqr__file_type__file_type_from_byte =
      _wire__bbqr__file_type__file_type_from_bytePtr
          .asFunction<void Function(int, int)>();

  void wire__bbqr__file_type__file_type_is_known_filetype(int port_, int byte) {
    return _wire__bbqr__file_type__file_type_is_known_filetype(port_, byte);
  }

  late final _wire__bbqr__file_type__file_type_is_known_filetypePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Uint8)>>(
        'frbgen_bull_sdk_wire__bbqr__file_type__file_type_is_known_filetype',
      );
  late final _wire__bbqr__file_type__file_type_is_known_filetype =
      _wire__bbqr__file_type__file_type_is_known_filetypePtr
          .asFunction<void Function(int, int)>();

  void wire__bitbox__api__get_btc_xpub(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> serial_number,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> keypath,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> xpub_type,
  ) {
    return _wire__bitbox__api__get_btc_xpub(
      port_,
      serial_number,
      keypath,
      xpub_type,
    );
  }

  late final _wire__bitbox__api__get_btc_xpubPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__bitbox__api__get_btc_xpub');
  late final _wire__bitbox__api__get_btc_xpub =
      _wire__bitbox__api__get_btc_xpubPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__bitbox__api__get_device_info(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> serial_number,
  ) {
    return _wire__bitbox__api__get_device_info(port_, serial_number);
  }

  late final _wire__bitbox__api__get_device_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__bitbox__api__get_device_info');
  late final _wire__bitbox__api__get_device_info =
      _wire__bitbox__api__get_device_infoPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__bitbox__api__get_root_fingerprint(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> serial_number,
  ) {
    return _wire__bitbox__api__get_root_fingerprint(port_, serial_number);
  }

  late final _wire__bitbox__api__get_root_fingerprintPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__bitbox__api__get_root_fingerprint');
  late final _wire__bitbox__api__get_root_fingerprint =
      _wire__bitbox__api__get_root_fingerprintPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  WireSyncRust2DartDco wire__bitbox__api__get_usb_write_data_wrapper(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> serial_number,
  ) {
    return _wire__bitbox__api__get_usb_write_data_wrapper(serial_number);
  }

  late final _wire__bitbox__api__get_usb_write_data_wrapperPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__bitbox__api__get_usb_write_data_wrapper');
  late final _wire__bitbox__api__get_usb_write_data_wrapper =
      _wire__bitbox__api__get_usb_write_data_wrapperPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__bitbox__api__init_app(int port_) {
    return _wire__bitbox__api__init_app(port_);
  }

  late final _wire__bitbox__api__init_appPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_bull_sdk_wire__bitbox__api__init_app',
      );
  late final _wire__bitbox__api__init_app = _wire__bitbox__api__init_appPtr
      .asFunction<void Function(int)>();

  void wire__bbqr__join__joined_frb_override_try_from_parts(
    int port_,
    ffi.Pointer<wire_cst_list_String> parts,
  ) {
    return _wire__bbqr__join__joined_frb_override_try_from_parts(port_, parts);
  }

  late final _wire__bbqr__join__joined_frb_override_try_from_partsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_String>)
        >
      >('frbgen_bull_sdk_wire__bbqr__join__joined_frb_override_try_from_parts');
  late final _wire__bbqr__join__joined_frb_override_try_from_parts =
      _wire__bbqr__join__joined_frb_override_try_from_partsPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_list_String>)>();

  WireSyncRust2DartDco wire__bitbox__api__set_usb_read_data_wrapper(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> serial_number,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> data,
  ) {
    return _wire__bitbox__api__set_usb_read_data_wrapper(serial_number, data);
  }

  late final _wire__bitbox__api__set_usb_read_data_wrapperPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_bull_sdk_wire__bitbox__api__set_usb_read_data_wrapper');
  late final _wire__bitbox__api__set_usb_read_data_wrapper =
      _wire__bitbox__api__set_usb_read_data_wrapperPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  void wire__bitbox__api__sign_psbt(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> serial_number,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> psbt_str,
    bool testnet,
  ) {
    return _wire__bitbox__api__sign_psbt(
      port_,
      serial_number,
      psbt_str,
      testnet,
    );
  }

  late final _wire__bitbox__api__sign_psbtPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Bool,
          )
        >
      >('frbgen_bull_sdk_wire__bitbox__api__sign_psbt');
  late final _wire__bitbox__api__sign_psbt = _wire__bitbox__api__sign_psbtPtr
      .asFunction<
        void Function(
          int,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          bool,
        )
      >();

  void wire__bbqr__split__split_frb_override_try_from_data(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> bytes,
    int file_type,
    ffi.Pointer<wire_cst_split_options> options,
  ) {
    return _wire__bbqr__split__split_frb_override_try_from_data(
      port_,
      bytes,
      file_type,
      options,
    );
  }

  late final _wire__bbqr__split__split_frb_override_try_from_dataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Int32,
            ffi.Pointer<wire_cst_split_options>,
          )
        >
      >('frbgen_bull_sdk_wire__bbqr__split__split_frb_override_try_from_data');
  late final _wire__bbqr__split__split_frb_override_try_from_data =
      _wire__bbqr__split__split_frb_override_try_from_dataPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              int,
              ffi.Pointer<wire_cst_split_options>,
            )
          >();

  void wire__bbqr__split__split_options_default(int port_) {
    return _wire__bbqr__split__split_options_default(port_);
  }

  late final _wire__bbqr__split__split_options_defaultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_bull_sdk_wire__bbqr__split__split_options_default',
      );
  late final _wire__bbqr__split__split_options_default =
      _wire__bbqr__split__split_options_defaultPtr
          .asFunction<void Function(int)>();

  void wire__bitbox__api__start_pairing(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> serial_number,
  ) {
    return _wire__bitbox__api__start_pairing(port_, serial_number);
  }

  late final _wire__bitbox__api__start_pairingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__bitbox__api__start_pairing');
  late final _wire__bitbox__api__start_pairing =
      _wire__bitbox__api__start_pairingPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  WireSyncRust2DartDco wire__ark_wallet__ark__utils__utils_is_ark(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> address,
  ) {
    return _wire__ark_wallet__ark__utils__utils_is_ark(address);
  }

  late final _wire__ark_wallet__ark__utils__utils_is_arkPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__ark_wallet__ark__utils__utils_is_ark');
  late final _wire__ark_wallet__ark__utils__utils_is_ark =
      _wire__ark_wallet__ark__utils__utils_is_arkPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__ark_wallet__ark__utils__utils_is_btc(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> address,
  ) {
    return _wire__ark_wallet__ark__utils__utils_is_btc(address);
  }

  late final _wire__ark_wallet__ark__utils__utils_is_btcPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__ark_wallet__ark__utils__utils_is_btc');
  late final _wire__ark_wallet__ark__utils__utils_is_btc =
      _wire__ark_wallet__ark__utils__utils_is_btcPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__bitbox__api__verify_address(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> serial_number,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> keypath,
    bool testnet,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> script_type,
  ) {
    return _wire__bitbox__api__verify_address(
      port_,
      serial_number,
      keypath,
      testnet,
      script_type,
    );
  }

  late final _wire__bitbox__api__verify_addressPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Bool,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_bull_sdk_wire__bitbox__api__verify_address');
  late final _wire__bitbox__api__verify_address =
      _wire__bitbox__api__verify_addressPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              bool,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__bbqr__qr__version_data_capacity(int port_, int that) {
    return _wire__bbqr__qr__version_data_capacity(port_, that);
  }

  late final _wire__bbqr__qr__version_data_capacityPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
        'frbgen_bull_sdk_wire__bbqr__qr__version_data_capacity',
      );
  late final _wire__bbqr__qr__version_data_capacity =
      _wire__bbqr__qr__version_data_capacityPtr
          .asFunction<void Function(int, int)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWalletPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_bull_sdk_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWalletPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWalletPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_bull_sdk_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWallet =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArkWalletPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_bull_sdk_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResultPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_bull_sdk_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResultPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_bull_sdk_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_bull_sdk_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_bull_sdk_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_bull_sdk_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClient =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEsploraClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDbPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_bull_sdk_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDbPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDbPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_bull_sdk_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDb =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInMemoryDbPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Int32> cst_new_box_autoadd_encoding(int value) {
    return _cst_new_box_autoadd_encoding(value);
  }

  late final _cst_new_box_autoadd_encodingPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int32> Function(ffi.Int32)>>(
        'frbgen_bull_sdk_cst_new_box_autoadd_encoding',
      );
  late final _cst_new_box_autoadd_encoding = _cst_new_box_autoadd_encodingPtr
      .asFunction<ffi.Pointer<ffi.Int32> Function(int)>();

  ffi.Pointer<ffi.Int32> cst_new_box_autoadd_file_type(int value) {
    return _cst_new_box_autoadd_file_type(value);
  }

  late final _cst_new_box_autoadd_file_typePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int32> Function(ffi.Int32)>>(
        'frbgen_bull_sdk_cst_new_box_autoadd_file_type',
      );
  late final _cst_new_box_autoadd_file_type = _cst_new_box_autoadd_file_typePtr
      .asFunction<ffi.Pointer<ffi.Int32> Function(int)>();

  ffi.Pointer<ffi.Int64> cst_new_box_autoadd_i_64(int value) {
    return _cst_new_box_autoadd_i_64(value);
  }

  late final _cst_new_box_autoadd_i_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int64> Function(ffi.Int64)>>(
        'frbgen_bull_sdk_cst_new_box_autoadd_i_64',
      );
  late final _cst_new_box_autoadd_i_64 = _cst_new_box_autoadd_i_64Ptr
      .asFunction<ffi.Pointer<ffi.Int64> Function(int)>();

  ffi.Pointer<wire_cst_split_options> cst_new_box_autoadd_split_options() {
    return _cst_new_box_autoadd_split_options();
  }

  late final _cst_new_box_autoadd_split_optionsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wire_cst_split_options> Function()>
      >('frbgen_bull_sdk_cst_new_box_autoadd_split_options');
  late final _cst_new_box_autoadd_split_options =
      _cst_new_box_autoadd_split_optionsPtr
          .asFunction<ffi.Pointer<wire_cst_split_options> Function()>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(ffi.Int32)
        >
      >('frbgen_bull_sdk_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_ark_transaction> cst_new_list_ark_transaction(
    int len,
  ) {
    return _cst_new_list_ark_transaction(len);
  }

  late final _cst_new_list_ark_transactionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_ark_transaction> Function(ffi.Int32)
        >
      >('frbgen_bull_sdk_cst_new_list_ark_transaction');
  late final _cst_new_list_ark_transaction = _cst_new_list_ark_transactionPtr
      .asFunction<ffi.Pointer<wire_cst_list_ark_transaction> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(ffi.Int32)
        >
      >('frbgen_bull_sdk_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_bull_sdk_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_split_options extends ffi.Struct {
  @ffi.Int32()
  external int encoding;

  @ffi.UintPtr()
  external int min_split_number;

  @ffi.UintPtr()
  external int max_split_number;

  @ffi.Int32()
  external int min_version;

  @ffi.Int32()
  external int max_version;
}

final class wire_cst_ArkTransaction_Boarding extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> txid;

  @ffi.Int64()
  external int sats;

  external ffi.Pointer<ffi.Int64> confirmed_at;
}

final class wire_cst_ArkTransaction_Commitment extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> txid;

  @ffi.Int64()
  external int sats;

  @ffi.Int64()
  external int created_at;
}

final class wire_cst_ArkTransaction_Redeem extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> txid;

  @ffi.Int64()
  external int sats;

  @ffi.Bool()
  external bool is_settled;

  @ffi.Int64()
  external int created_at;
}

final class ArkTransactionKind extends ffi.Union {
  external wire_cst_ArkTransaction_Boarding Boarding;

  external wire_cst_ArkTransaction_Commitment Commitment;

  external wire_cst_ArkTransaction_Redeem Redeem;
}

final class wire_cst_ark_transaction extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external ArkTransactionKind kind;
}

final class wire_cst_list_ark_transaction extends ffi.Struct {
  external ffi.Pointer<wire_cst_ark_transaction> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_ark_boarding extends ffi.Struct {
  @ffi.Int64()
  external int unconfirmed;

  @ffi.Int64()
  external int confirmed;

  @ffi.Int64()
  external int total;
}

final class wire_cst_ark_balance extends ffi.Struct {
  @ffi.Int64()
  external int preconfirmed;

  @ffi.Int64()
  external int settled;

  @ffi.Int64()
  external int available;

  @ffi.Int64()
  external int recoverable;

  @ffi.Int64()
  external int total;

  external wire_cst_ark_boarding boarding;
}

final class wire_cst_boarding_settlement extends ffi.Struct {
  @ffi.Int32()
  external int pending_count;

  @ffi.Int32()
  external int confirmed_count;

  @ffi.Int64()
  external int total_pending_sats;

  @ffi.Int64()
  external int total_confirmed_sats;
}

final class wire_cst_device_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> version;

  @ffi.Bool()
  external bool initialized;
}

final class wire_cst_joined extends ffi.Struct {
  @ffi.Int32()
  external int encoding;

  @ffi.Int32()
  external int file_type;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> data;
}

final class wire_cst_server_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> version;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> signer_pubkey;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> forfeit_pubkey;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> forfeit_address;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> checkpoint_tapscript;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> network;

  @ffi.Int64()
  external int session_duration;

  @ffi.Uint32()
  external int unilateral_exit_delay;

  @ffi.Uint32()
  external int boarding_exit_delay;

  external ffi.Pointer<ffi.Int64> utxo_min_amount;

  external ffi.Pointer<ffi.Int64> utxo_max_amount;

  external ffi.Pointer<ffi.Int64> vtxo_min_amount;

  external ffi.Pointer<ffi.Int64> vtxo_max_amount;

  @ffi.Int64()
  external int dust;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> digest;
}

final class wire_cst_split extends ffi.Struct {
  @ffi.Int32()
  external int version;

  external ffi.Pointer<wire_cst_list_String> parts;

  @ffi.Int32()
  external int encoding;
}

final class wire_cst_utils extends ffi.Opaque {}
