// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'status.dart';

// These functions are ignored because they are not marked as `pub`: `client`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `status_stream`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TorService>>
abstract class TorService implements RustOpaqueInterface {
  /// Bootstrap, resolving when the client is usable.
  Future<void> bootstrap();

  /// Open and immediately close a circuit to `host:port`, returning how long
  /// it took.
  ///
  /// This is the canary that separates "the Tor network is unreachable" from
  /// "our Electrum server is down". It goes through `TorClient::connect`
  /// directly, bypassing both the SOCKS listener and the application's
  /// servers, so a success here means Tor genuinely carries traffic.
  ///
  /// `ready_for_traffic` is not a substitute: it means "a request can be
  /// started", not "a request succeeded".
  ///
  /// Times are milliseconds: FRB has no outbound mapping for
  /// `std::time::Duration`, and an integer keeps `chrono` out of our types.
  Future<int> probe({
    required String host,
    required int port,
    required int timeoutMs,
  });

  /// Whether the SOCKS accept loop is still running.
  ///
  /// It can die on its own — a listener error ends it — after which every
  /// connection to [`TorService::socks_port`] is refused. Without this, the
  /// app would see unexplained connection failures from BDK and blame the
  /// network. Cheap enough to check before handing the port out.
  Future<bool> proxyIsAlive();

  /// Put background activity to sleep, or wake it up.
  Future<void> setDormant({required bool dormant});

  /// The port the SOCKS proxy is actually listening on.
  Future<int> socksPort();

  /// Create the client and bind the SOCKS listener. Does not bootstrap.
  ///
  /// `socks_port` may be `0` to let the OS choose; read the real value back
  /// from [`TorService::socks_port`].
  static Future<TorService> start({
    required String stateDir,
    required String cacheDir,
    required int socksPort,
  }) => OnionCore.instance.api.crateApiClientTorServiceStart(
    stateDir: stateDir,
    cacheDir: cacheDir,
    socksPort: socksPort,
  );

  /// Current readiness snapshot.
  Future<TorStatus> status();

  /// Stop the proxy listener, bootstrap, and status-forwarding tasks.
  ///
  /// Safe to call more than once. Keeping this as `&self` is required by the
  /// FFI boundary: a status-stream task may briefly hold another opaque
  /// reference, so consuming `self` could panic while decoding the call.
  Future<void> stop();

  /// Start forwarding readiness changes to Dart in a background task.
  ///
  /// Same data as [`TorService::status_stream`], expressed as a
  /// [`StreamSink`] because that is the only stream shape
  /// `flutter_rust_bridge` generates for. The task ends when Dart drops the
  /// subscription, arti closes the channel, or [`TorService::stop`] runs.
  Stream<TorStatus> watchStatus();
}
